apiVersion: apps/v1
kind: Deployment
metadata:
  name: sda-orchestrate
  namespace: demo
spec:
  selector:
    matchLabels:
      app: sda-orchestrate
  replicas: 1
  template:
    metadata:
      labels:
        app: sda-orchestrate
    spec:
      containers:
      - name: sda-orchestrate
        image: "cscfi/sda-orchestrate:latest"
        env:
          - name: DB_LEGA_OUT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: orchestrate-secret
                key: dbout
          - name: DB_LEGA_IN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: orchestrate-secret
                key: dbin
          - name: DB_HOST
            value: ""
          - name: BROKER_HOST
            value: ""
          - name: BROKER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: orchestrate-secret
                key: mqPassword
          - name: BROKER_PORT
            value: "5670"
          - name: BROKER_USERNAME
            value: ""
          - name: BROKER_VHOST
            value: "lega"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
          - name: webapp
            containerPort: 5050
        volumeMounts:
          - name: tls
            mountPath: /tls
      volumes:
        - name: tls
          secret:
            secretName: orhestrate-certs
---
apiVersion: v1
kind: Service
metadata:
  name: sda-orchestrate
  namespace: demo
  labels:
    app: sda-orchestrate
spec:
  ports:
    - name: webapp
      port: 5050
      targetPort: webapp
      protocol: TCP
  selector:
    app: sda-orchestrate
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sda-orchestrate
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sda-orchestrate
          servicePort: 80
---
apiVersion: v1
data:
  dbin: ""
  dbout: ""
  mqPassword: ""
kind: Secret
metadata:
  name: orchestrate-secret
  namespace: demo
type: Opaque
---
apiVersion: v1
data:
  root.ca.crt: ""
  cert.ca.crt: ""
  cert.ca.key: ""
kind: Secret
metadata:
  name: orhestrate-certs
  namespace: demo
type: Opaque
